name: Build RPM for holoscan-proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: fedora:39

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:  
          fetch-depth: 0

      - name: Install dependencies
        run: |
          dnf install -y \
            rpm-build \
            rpmdevtools \
            git \
            cmake \
            gcc-c++ \
            make \
            cppzmq-devel \
            yaml-cpp-devel

      - name: Prepare rpmbuild structure
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros

      - name: Create source tarball with git archive
        run: |
          VERSION=0.0.0
          git archive --format=tar.gz --prefix=holoscan-proxy-${VERSION}/ HEAD > ~/rpmbuild/SOURCES/holoscan-proxy-${VERSION}.tar.gz

      - name: Copy spec file
        run: |
          cp packaging/holoscan-proxy.spec ~/rpmbuild/SPECS/

      - name: Build RPM
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/holoscan-proxy.spec

      - name: Upload built RPMs
        uses: actions/upload-artifact@v4
        with:
          name: holoscan-proxy-rpms
          path: ~/rpmbuild/RPMS/**/*.rpm
