jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          dnf install -y rpm-build cmake gcc-c++ make cppzmq-devel yaml-cpp-devel

      - name: Prepare rpmbuild directories
        run: mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

      - name: Create source tarball
        run: |
          tar czf ~/rpmbuild/SOURCES/holoscan-proxy-0.0.0.tar.gz --exclude='.git' .

      - name: Copy spec file
        run: cp packaging/holoscan-proxy.spec ~/rpmbuild/SPECS/

      - name: Build RPM
        run: rpmbuild -ba ~/rpmbuild/SPECS/holoscan-proxy.spec

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v3
        with:
          name: holoscan-proxy-rpm
          path: ~/rpmbuild/RPMS/x86_64/*.rpm
