name: Build RPM Package

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-rpm:
    runs-on: ubuntu-latest # Use an Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Get your code
      with:
        fetch-depth: 0

    - name: Install RPM build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm build-essential rpmlint cmake gcc-14 g++-14 make libzmq3-dev libyaml-cpp-dev
       
    - name: Prepare RPM build environment
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp packaging/holoscan-proxy.spec ~/rpmbuild/SPECS/ # Copy your spec file
        # Copy source files to ~/rpmbuild/SOURCES if needed
        # For example: cp your-source-code.tar.gz ~/rpmbuild/SOURCES/

    - name: Check for .git
      run: ls -la . | grep .git || echo ".git is missing!"

    - name: Create source tarball from git
      run: |
        VERSION=0.0.0
        ARCHIVE=holoscan-proxy-${VERSION}.tar.gz
        echo "Creating $ARCHIVE..."
        git archive --format=tar.gz --prefix=holoscan-proxy-${VERSION}/ HEAD -o $ARCHIVE

        if [ ! -f "$ARCHIVE" ]; then
          echo "❌ Error: Tarball not created."
          exit 1
        fi

        mv $ARCHIVE ~/rpmbuild/SOURCES/

    - name: Check GCC version
      run: gcc --version

    - name: Build RPM package
      run: rpmbuild -ba --nodeps ~/rpmbuild/SPECS/holoscan-proxy.spec # Build the RPM

    - name: Upload RPM artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpm-package
        path: ~/rpmbuild/RPMS/**/*.rpm # Upload the generated RPMs

