name: Build and Upload RPM (AlmaLinux 8)

on:
  push:
    branches:
      - main

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    container:
      image: almalinux:8

    steps:
    - name: Install build dependencies
      run: |
        dnf -y groupinstall "Development Tools"
        dnf -y install epel-release dnf-plugins-core
        dnf config-manager --set-enabled powertools
        dnf makecache
        dnf -y install rpm-build rpmdevtools git tar cmake \
          gcc-c++ make rpmlint which \
          zeromq-devel yaml-cpp-devel

    - name: Add build user and setup RPM env
      run: |
        useradd builder || true
        mkdir -p /home/builder/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        chown -R builder:builder /home/builder
        echo '%_topdir /home/builder/rpmbuild' > /home/builder/.rpmmacros

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create source tarball and copy spec
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

        VERSION=0.0.0
        ARCHIVE=holoscan-proxy-${VERSION}.tar.gz
        git archive --format=tar.gz --prefix=holoscan-proxy-${VERSION}/ HEAD -o $ARCHIVE

        cp packaging/holoscan-proxy.spec /home/builder/rpmbuild/SPECS/
        mv $ARCHIVE /home/builder/rpmbuild/SOURCES/
        chown -R builder:builder /home/builder/rpmbuild

    - name: Build the RPM
      run: |
        su - builder -c "rpmbuild -ba /home/builder/rpmbuild/SPECS/holoscan-proxy.spec"

    - name: Upload RPM as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpm-package
        path: /home/builder/rpmbuild/RPMS/**/*.rpm
